// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// call_rpart_
List call_rpart_(SEXP formula_obj, Function wrap_rpart, DataFrame newdata, NumericVector weight_vec, SEXP classname_map);
RcppExport SEXP fastAdaboost_call_rpart_(SEXP formula_objSEXP, SEXP wrap_rpartSEXP, SEXP newdataSEXP, SEXP weight_vecSEXP, SEXP classname_mapSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type formula_obj(formula_objSEXP);
    Rcpp::traits::input_parameter< Function >::type wrap_rpart(wrap_rpartSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type newdata(newdataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weight_vec(weight_vecSEXP);
    Rcpp::traits::input_parameter< SEXP >::type classname_map(classname_mapSEXP);
    __result = Rcpp::wrap(call_rpart_(formula_obj, wrap_rpart, newdata, weight_vec, classname_map));
    return __result;
END_RCPP
}
// adaboost_main_loop_
List adaboost_main_loop_(SEXP formula_obj, DataFrame data_df, int nIter, Function wrap_rpart, IntegerVector vardep, SEXP classname_map, std::string boost_method);
RcppExport SEXP fastAdaboost_adaboost_main_loop_(SEXP formula_objSEXP, SEXP data_dfSEXP, SEXP nIterSEXP, SEXP wrap_rpartSEXP, SEXP vardepSEXP, SEXP classname_mapSEXP, SEXP boost_methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type formula_obj(formula_objSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type data_df(data_dfSEXP);
    Rcpp::traits::input_parameter< int >::type nIter(nIterSEXP);
    Rcpp::traits::input_parameter< Function >::type wrap_rpart(wrap_rpartSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type vardep(vardepSEXP);
    Rcpp::traits::input_parameter< SEXP >::type classname_map(classname_mapSEXP);
    Rcpp::traits::input_parameter< std::string >::type boost_method(boost_methodSEXP);
    __result = Rcpp::wrap(adaboost_main_loop_(formula_obj, data_df, nIter, wrap_rpart, vardep, classname_map, boost_method));
    return __result;
END_RCPP
}
// calculate_test_error_
double calculate_test_error_(IntegerVector vardep, IntegerVector predicted_class_int);
RcppExport SEXP fastAdaboost_calculate_test_error_(SEXP vardepSEXP, SEXP predicted_class_intSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type vardep(vardepSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type predicted_class_int(predicted_class_intSEXP);
    __result = Rcpp::wrap(calculate_test_error_(vardep, predicted_class_int));
    return __result;
END_RCPP
}
// predict_adaboost_
List predict_adaboost_(List tree_list, NumericVector coeff_vector, DataFrame newdata, int num_examples, Function wrap_rpart_predict, SEXP classnames_map);
RcppExport SEXP fastAdaboost_predict_adaboost_(SEXP tree_listSEXP, SEXP coeff_vectorSEXP, SEXP newdataSEXP, SEXP num_examplesSEXP, SEXP wrap_rpart_predictSEXP, SEXP classnames_mapSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type tree_list(tree_listSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type coeff_vector(coeff_vectorSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type newdata(newdataSEXP);
    Rcpp::traits::input_parameter< int >::type num_examples(num_examplesSEXP);
    Rcpp::traits::input_parameter< Function >::type wrap_rpart_predict(wrap_rpart_predictSEXP);
    Rcpp::traits::input_parameter< SEXP >::type classnames_map(classnames_mapSEXP);
    __result = Rcpp::wrap(predict_adaboost_(tree_list, coeff_vector, newdata, num_examples, wrap_rpart_predict, classnames_map));
    return __result;
END_RCPP
}
// predict_real_adaboost_
List predict_real_adaboost_(List tree_list, NumericVector coeff_vector, DataFrame newdata, int num_examples, Function wrap_rpart_predict_real);
RcppExport SEXP fastAdaboost_predict_real_adaboost_(SEXP tree_listSEXP, SEXP coeff_vectorSEXP, SEXP newdataSEXP, SEXP num_examplesSEXP, SEXP wrap_rpart_predict_realSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type tree_list(tree_listSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type coeff_vector(coeff_vectorSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type newdata(newdataSEXP);
    Rcpp::traits::input_parameter< int >::type num_examples(num_examplesSEXP);
    Rcpp::traits::input_parameter< Function >::type wrap_rpart_predict_real(wrap_rpart_predict_realSEXP);
    __result = Rcpp::wrap(predict_real_adaboost_(tree_list, coeff_vector, newdata, num_examples, wrap_rpart_predict_real));
    return __result;
END_RCPP
}
